# Generated by Django 2.2.7 on 2020-12-02 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sal', models.FloatField()),
            ],
            options={
                'db_table': 'emp_info',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adrref', to='sampleapp.Employee')),
            ],
            options={
                'db_table': 'adr_info',
            },
        ),
    ]
