# Generated by Django 2.2.7 on 2020-12-02 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='emp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adrref', to='sampleapp.Employee'),
        ),
    ]
